### ISSUE TITLE
feature: listViews

### ISSUE THREAD

**Issue by profit0124** [HwaNaHouse/ios-MC2-Moment#14]
### TODO
- [x] CategoryListView 추가하기
- [x] PinListView 추가하기
- [x] 화면전환 효과 (CategoryListView, PinListView)
- [x] CategoryListView 와 Category생성뷰 연결하기
- [x] PinListView와 PinDetailView 연결하기
- [x] 코어데이터 attribute 수정
- [x] 코어데이터 연결하기
- [ ] ViewModel 생성
- [x] 이모티콘 테두리와 함께 생성해주는 컴퍼넌트
- [x] 코어데이터 연결 후 데이터 변화에 따른 버그 픽스
- [x] TNSheet 모드 보완
- [ ] 코어데이터 접근을 위한 프로퍼티 수정
- [x] 핀 삭제 기능 

### 비고 및 한계
*해당 이슈에서 해결하지 못한 사항들*
- 코어데이터 수정하며, 기존 파일들에서 사용했던 변수명 변경 진행

---
> 진행 상황은 Comment로 아래에 달아주세요
ex) 220405: 00 추가
