### ISSUE TITLE
checklist before release

### ISSUE THREAD

**Issue by BrightHyeon** [HwaNaHouse/ios-MC2-Moment#26]
### TODO
- [ ] Light Mode로 고정
- [ ] 세로모드 전용으로 고정
- [ ] 권한에 따른 기능제한
- [ ] 앨범 접근권한 추가하기
